version: "3.8"

services:
  database:
    platform: linux/x86_64
    image: mysql:5.7.23
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "digital-menu_db"
    ports:
      - "3306:3306"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      